// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDY9sbLQNpvu6n-lVqLrE1a4R5UsEBxUwA',
    appId: '1:401447266637:web:abd8d2d5d8884b6589ef04',
    messagingSenderId: '401447266637',
    projectId: 'flutterexam1-77c07',
    authDomain: 'flutterexam1-77c07.firebaseapp.com',
    storageBucket: 'flutterexam1-77c07.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVHG732mHYkcSlKxdnMU-Xy7jGTgZP578',
    appId: '1:401447266637:android:1be669c1e4a3ac1a89ef04',
    messagingSenderId: '401447266637',
    projectId: 'flutterexam1-77c07',
    storageBucket: 'flutterexam1-77c07.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-HS6X6UdT42dIKtqWy2PnHauZTiIEIVs',
    appId: '1:401447266637:ios:a639afc12dd9231f89ef04',
    messagingSenderId: '401447266637',
    projectId: 'flutterexam1-77c07',
    storageBucket: 'flutterexam1-77c07.appspot.com',
    iosClientId: '401447266637-hqnvtcn0si07a6ulo9cmjrpf4eine2vp.apps.googleusercontent.com',
    iosBundleId: 'com.example.examFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-HS6X6UdT42dIKtqWy2PnHauZTiIEIVs',
    appId: '1:401447266637:ios:a639afc12dd9231f89ef04',
    messagingSenderId: '401447266637',
    projectId: 'flutterexam1-77c07',
    storageBucket: 'flutterexam1-77c07.appspot.com',
    iosClientId: '401447266637-hqnvtcn0si07a6ulo9cmjrpf4eine2vp.apps.googleusercontent.com',
    iosBundleId: 'com.example.examFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDY9sbLQNpvu6n-lVqLrE1a4R5UsEBxUwA',
    appId: '1:401447266637:web:9fe31a2b70d94ac689ef04',
    messagingSenderId: '401447266637',
    projectId: 'flutterexam1-77c07',
    authDomain: 'flutterexam1-77c07.firebaseapp.com',
    storageBucket: 'flutterexam1-77c07.appspot.com',
  );

}